{{- if .Values.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: binderhub
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: binder
              servicePort: 80
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
{{- end }}
