kind: Secret
apiVersion: v1
metadata:
  name: binder-secret
type: Opaque
stringData:
  {{- /* Make it easy to mount certain parts without traversing YAML */}}
  binder.hub-token: {{ .Values.jupyterhub.hub.services.binder.apiToken | quote }}

  {{- /* Stash away all Helm template values */}}
  values.yaml: |
    {{- .Values | toYaml | nindent 4 }}

  {{- /* Glob files to allow them to be mounted by the binderhub pod */}}
  {{- /* key=filename: value=content */}}
  {{- (.Files.Glob "files/*").AsConfig | nindent 2 }}
---
{{- if .Values.config.BinderHub.use_registry }}
kind: Secret
apiVersion: v1
metadata:
  name: binder-push-secret
type: Opaque
data:
  config.json: {{ include "registryDockerConfig" . | b64enc | quote }}
{{- end }}
