{{- $HTTPS := (and .Values.jupyterhub.proxy.https.hosts .Values.jupyterhub.proxy.https.enabled) }}
{{- $autoHTTPS := (and $HTTPS (eq .Values.jupyterhub.proxy.https.type "letsencrypt")) }}
{{- if (and $autoHTTPS .Values.rbac.enabled) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: binder-autohttps
  labels:
    app: binder
    component: autohttps
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autohttps
  labels:
    app: binder
    component: autohttps
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: autohttps
  apiGroup:
roleRef:
  kind: Role
  name: autohttps
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autohttps
  labels:
    app: binder
    component: autohttps
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
