{{- $HTTPS := (and .Values.jupyterhub.proxy.https.hosts .Values.jupyterhub.proxy.https.enabled) }}
{{- $autoHTTPS := (and $HTTPS (eq .Values.jupyterhub.proxy.https.type "letsencrypt")) }}
{{- if $autoHTTPS -}}
apiVersion: v1
kind: Service
metadata:
  name: binder-https
  labels:
    app: binder
    component: autohttps
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations: {{ .Values.jupyterhub.proxy.service.annotations | toJson }}
spec:
  type: ClusterIP
  selector:
    app: binder
    component: autohttps
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: binder
{{- end }}
